# Generated by Django 3.2 on 2021-04-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_diabetes'),
    ]

    operations = [
        migrations.AddField(
            model_name='diabetes',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
