# Generated by Django 3.2 on 2021-04-29 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20210429_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='appointments',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='customer.appointment'),
        ),
    ]
